import type { Metadata } from "next";
import { Nunito_Sans } from "next/font/google";
import "./globals.css";

const nunitoSans = Nunito_Sans({
  variable: "--font-nunito-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${nunitoSans.className} antialiased`}>
        <div>
          <div className="h-[495px] w-full bg-linear-to-b from-[#F5F8FF] to-[#DBF5FF]">
            <div>Tripzy</div>
          </div>
          {children}
        </div>
      </body>
    </html>
  );
}
